In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([-3,1,1])

In [5]:
np.dot(a,b)

2

In [6]:
np.arange(1, 2, 0.3, dtype=float)

array([ 1. ,  1.3,  1.6,  1.9])

In [7]:
numpy.array(1, 2, 3, 4, 5, dtype=float)

NameError: name 'numpy' is not defined

In [8]:
np.array([True,False,True])

array([ True, False,  True], dtype=bool)

In [12]:
?np.array

In [14]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])

In [17]:
a*b

array([ 0, -7, 22])

In [19]:
b.dot(a)

15

In [22]:
np.dot(a,b)

15

In [25]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [24]:
c = np.eye((4, 5))

TypeError: 'tuple' object cannot be interpreted as an index

In [27]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [28]:
np.ones((10, 10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [29]:
    np.eye(2, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [33]:
a = np.eye(4, 5)
a.shape

(4L, 5L)

In [35]:
a[[0, 3], [1, 3]]

array([ 0.,  1.])

In [37]:
np.eye(4, 5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])